version: '3.3'

services:

    synapse:
        image: docker.io/matrixdotorg/synapse:latest
        restart: always
        environment:
            - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
        volumes:
            - ./synapse_data:/data
        depends_on:
            - database

    web:
        image: vectorim/element-web:latest
        volumes:
            - ./element-config.json:/app/config.localhost.json:ro

    # We set-up an NGINX to have a unique endpoint for app (web) & api (synapse)
    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:80" # auto-redirect to HTTPS
            - "8443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/matrix.conf:ro
            - ./nginx_logs:/var/log/nginx
            - ./synapse_data:/synapse_data:ro
        depends_on:
            - synapse
            - web

    database:
        image: postgres:13.2-alpine
        restart: always
        environment:
            - POSTGRES_DB=synapse
            - POSTGRES_USER=synapse_user
            - POSTGRES_PASSWORD=synapse_password
            # ensure the database gets created correctly
            # https://github.com/matrix-org/synapse/blob/master/docs/postgres.md#set-up-database
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
        volumes:
            # You may store the database tables in a local folder..
            - database:/var/lib/postgresql/data

volumes:
    database:
