version: '3.3'

services:

    synapse:
        image: docker.io/matrixdotorg/synapse:latest
        restart: always
        environment:
            - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
        volumes:
            - ./synapse_data:/data
        depends_on:
            - database
        # In order to expose Synapse, remove one of the following, you might for
        # instance expose the TLS port directly:
        ports:
            - 8448:8448

    web:
        image: vectorim/element-web:latest
        volumes:
            - ./element-config.json:/app/config.localhost.json:ro
        ports:
            - 8080:80

    database:
        image: postgres:13.2-alpine
        restart: always
        environment:
            - POSTGRES_DB=synapse
            - POSTGRES_USER=synapse_user
            - POSTGRES_PASSWORD=synapse_password
            # ensure the database gets created correctly
            # https://github.com/matrix-org/synapse/blob/master/docs/postgres.md#set-up-database
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
        volumes:
            # You may store the database tables in a local folder..
            - database:/var/lib/postgresql/data

volumes:
    database:
